package com.amator.htprinter.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.amator.htprinter.module.Banner;
import com.amator.htprinter.module.HomePage;

import com.amator.htprinter.dao.BannerDao;
import com.amator.htprinter.dao.HomePageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerDaoConfig;
    private final DaoConfig homePageDaoConfig;

    private final BannerDao bannerDao;
    private final HomePageDao homePageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerDaoConfig = daoConfigMap.get(BannerDao.class).clone();
        bannerDaoConfig.initIdentityScope(type);

        homePageDaoConfig = daoConfigMap.get(HomePageDao.class).clone();
        homePageDaoConfig.initIdentityScope(type);

        bannerDao = new BannerDao(bannerDaoConfig, this);
        homePageDao = new HomePageDao(homePageDaoConfig, this);

        registerDao(Banner.class, bannerDao);
        registerDao(HomePage.class, homePageDao);
    }
    
    public void clear() {
        bannerDaoConfig.clearIdentityScope();
        homePageDaoConfig.clearIdentityScope();
    }

    public BannerDao getBannerDao() {
        return bannerDao;
    }

    public HomePageDao getHomePageDao() {
        return homePageDao;
    }

}
